### PR TITLE
Uses at_dervice to generate the easier AT command boilerplate

### PR DESCRIPTION
**Pull request by stephanh**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi. I'm not yet sure whether I want to use `at_derive` or not. It has a few tradeoffs, the downsides are more dependencies (larger binaries) as well as higher memory usage (because custom-written implementations know a bit more about their potential memory use than derived ones). The second aspect might be solvable, but we're still left with the additional dependencies.

Another aspect is that serde is used for deserializing, and I'm not yet sure whether serde can handle all types of parsing that we need to do (the structure of the responses is different from device to device). Of course we could always fall back to parsing just as a string and then doing manual decoding afterwards.

I did consider using the derive macros initially, but right now I'd prefer to wait until all commands are implemented (there aren't *that* many). An experimental branch could then try to convert to the macros, to see whether they bring an improvement (and what the tradeoffs are). Would you agree with that?

**Comment by stephanh** [comment]
Ok. For those places we can implement it. It saves quite a bit of repetitive code which I thought would make the code base more accessible/easier to work with.

We could also look into only using the macro for creating the commands and moving the parsing implementation into the response and hand coding that? That will address the inefficiencies but not the larger binary issue.

**Comment by dbrgn** [comment]
> We could also look into only using the macro for creating the commands

As far as I know, derive macros cannot derive only parts of a trait, but I could be wrong.

I thought about creating our own macros that handle the repetitive code for us but doesn't add a dependency on serde. Maybe something like this:

```rust
impl AtatCmd for PrepareSendData {
    simple_command!("AT+CIPSTATUS", types::ConnectionStatus);

    fn parse(...) ...
}
```

...which would result in:

```rust
impl AtatCmd for PrepareSendData {
    type CommandLen = heapless::consts::U14;
    type Response = types::ConnectionStatus;

    fn as_string(&self) -> String<Self::CommandLen> {
        String::from("AT+CIPSTATUS\r\n")
    }

    fn parse(...) ...
}
```

(I'm pretty sure we could calculate the string constant length at compile time and turn it into a typenum type.)

However, I *think* this requires [proc_macro_hygiene](https://doc.rust-lang.org/nightly/unstable-book/language-features/proc-macro-hygiene.html) and thus will only work on nightly.

We'd probably have to generate the entire impl block from the macro, so something like this:

```rust
atat_cmd!(
    "AT+CIPSTATUS",
    types::ConnectionStatus,
    fn parse(...) ...
)
```

Here I'm not 100% sure whether we can just make a function definition an "argument" of a macro.

**Comment by dbrgn** [comment]
Closing for now.

**Pull request closed without merging**
